### ISSUE TITLE
Using "http" method fails on username/password prompt

### ISSUE THREAD

**Issue by dirkhas** [ezbz/gitlabber#76] opened 2021-05-11 13:08 UTC
When setting method to "http", the scripts end up prompting for username/password. This makes it impossible to script gitlabber non-interactively.
The correct way would probably be to:

1. Make user specify username in addition to token on command-line, and use these.
2. Integrate with git credentials to get this info.

**Comment by ezbz** [comment] 2021-07-10 06:54
@dirkhas  could you please provide the command you're trying to run, the OS, the python version and the output in verbose mode?

**Comment by ezbz** [comment] 2021-07-12 18:09
duplicate of #18

**Closed by ezbz** 2021-07-12 18:09 UTC
