### ISSUE TITLE
Ignore custom Gitlab certificates

### ISSUE THREAD

**Issue by gchr** [ezbz/gitlabber#67] opened 2021-04-01 08:20 UTC
We are using an internal on-premises Gitlab instance with custom certificate.
Is there a way (option?) to bypass the certificate verification?

`
Traceback (most recent call last):
  File "/home/username/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/username/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/username/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/username/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/home/username/anaconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/username/anaconda3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/username/anaconda3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/username/anaconda3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

`

**Comment by ezbz** [comment] 2021-04-07 07:51
@gchr you can turn it off globally I think via:

```
git config --global http.sslVerify false
```

Also see reference in #35 which allows to provide a custom CA path

**Comment by ezbz** [comment] 2021-04-07 07:52
Duplicate of #14

**Closed by ezbz** 2021-04-07 07:51 UTC
