### ISSUE TITLE
Does it work on gitlab cloud ?

### ISSUE THREAD

**Issue by prince11jose** [ezbz/gitlabber#79] opened 2021-06-08 07:27 UTC
I've been trying to use gitlabber  but it  does not seem to work it gitlab cloud

**Comment by prince11jose** [comment] 2021-06-08 07:30
My base url is : https://gitlab.com/<group-name>

**Comment by ezbz** [comment] 2021-07-10 06:45
duplicate of https://github.com/ezbz/gitlabber/issues/28

**Closed by ezbz** 2021-07-10 06:45 UTC
