### ISSUE TITLE
Use access token to clone repo

### ISSUE THREAD

**Issue by syphernl** [ezbz/gitlabber#97] opened 2022-03-09 12:49 UTC
**Is your feature request related to a problem? Please describe.**
Currently using `--method http` results in getting a question for username / password. 
Within GitLab it is however possible to use the access token (assuming it has `read_repository` permissions) to clone the repo.

**Describe the solution you'd like**
Append the token to the URL

**Describe alternatives you've considered**
None

**Additional context**

**Comment by ezbz** [comment] 2022-03-12 13:42
Duplicate of #18 

GitPython doesn't support this natively you can add a wrapper as described [here](https://stackoverflow.com/questions/44784828/gitpython-git-authentication-using-user-and-password)

**Comment by NiMeDia** [comment] 2023-01-13 10:28
In gitlab the username would be "oauth2" and the password would be the access token

**Closed** 2023-10-20 14:26 UTC
