### ISSUE TITLE
Fails at 503 checking browser

### ISSUE THREAD

**Issue by rikoz** [ezbz/gitlabber#78] opened 2021-05-25 17:20 UTC
![Screenshot from 2021-05-25 18-19-19](https://user-images.githubusercontent.com/6421629/119540852-d06c7180-bd85-11eb-9c00-641f9ef09645.png)

**Comment by ezbz** [comment] 2021-07-10 06:46
duplicate of https://github.com/ezbz/gitlabber/issues/30

**Closed by ezbz** 2021-07-10 06:46 UTC
