### ISSUE TITLE
Clone into "path" not "name"

### ISSUE THREAD

**Issue by gregbacchus** [ezbz/gitlabber#38] opened 2021-01-10 21:36 UTC
This seems like a really useful tool, however I don't understand why it would clone into directories that use the project/group name rather than the "path" from Gitlab?

Maybe an option could be made to clone into directories based on the Gitlab path?

**Comment by kebroman** [comment] 2021-01-11 15:54
+1 for using the rest path vs. project/group names

**Comment by ziegenberg** [comment] 2021-01-19 11:55
This seems to be a duplicate of #25.

**Comment by ezbz** [comment] 2021-01-28 13:41
@gregbacchus one issue with allowing this is that it will not be interchangeable across runs when use of the parameter changes

say u did one run with path and then another with names you will get a double structure, this complicates things

**Comment by ziegenberg** [comment] 2021-01-28 14:42
This is correct. You would have to stick with one method. Or find some way to detect the way it was run the last time.

**Comment by ahmadalli** [comment] 2021-02-08 08:18
> @gregbacchus one issue with allowing this is that it will not be interchangeable across runs when use of the parameter changes
> 
> say u did one run with path and then another with names you will get a double structure, this complicates things

I'm new to this project and I'm not aware of the scope of its abilities, my question is what happens if users change the name of their project on gitlab? wouldn't that cause a double structure?

**Comment by ahmadalli** [comment] 2021-02-10 07:42
also what will happen if there exists some projects with the same name on a group (since gitlab assures path uniqueness, not name  uniqueness)

**Comment by gregbacchus** [comment] 2021-02-12 07:17
> @gregbacchus one issue with allowing this is that it will not be interchangeable across runs when use of the parameter changes
> 
> say u did one run with path and then another with names you will get a double structure, this complicates things

I don't see any problem there. Running with the same arguments is about as important as running it in the same target location. Changing either could result in duplication.

**Comment by ezbz** [comment] 2021-02-21 14:01
> what happens if users change the name of their project on gitlab? wouldn't that cause a double structure?

true that one project will be duplicate locally gitlabber doesn't maintain any local state (i.e., project ids)

**Comment by ezbz** [comment] 2021-02-21 14:02
> also what will happen if there exists some projects with the same name on a group (since gitlab assures path uniqueness, not name uniqueness)

For that reason I originally chose project paths for the local folder structure

**Comment by ezbz** [comment] 2021-02-21 14:51
Duplicate of #25

**Closed by ezbz** 2021-02-21 14:51 UTC
